//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SimpleRESTClient.WcfSimpleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfSimpleServiceReference.IEcho")]
    public interface IEcho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEcho/GetData", ReplyAction="http://tempuri.org/IEcho/GetDataResponse")]
        string GetData(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEcho/GetData", ReplyAction="http://tempuri.org/IEcho/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEchoChannel : WCF_SimpleRESTClient.WcfSimpleServiceReference.IEcho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EchoClient : System.ServiceModel.ClientBase<WCF_SimpleRESTClient.WcfSimpleServiceReference.IEcho>, WCF_SimpleRESTClient.WcfSimpleServiceReference.IEcho {
        
        public EchoClient() {
        }
        
        public EchoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EchoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EchoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EchoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string msg) {
            return base.Channel.GetData(msg);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string msg) {
            return base.Channel.GetDataAsync(msg);
        }
    }
}
