//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSF_SimpleRESTClient_1.FlightsReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="http://schemas.datacontract.org/2004/07/WcfSimpleService")]
    [System.SerializableAttribute()]
    public partial class Flight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipCountryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryDate {
            get {
                return this.DeliveryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryDateField, value) != true)) {
                    this.DeliveryDateField = value;
                    this.RaisePropertyChanged("DeliveryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightDate {
            get {
                return this.FlightDateField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightDateField, value) != true)) {
                    this.FlightDateField = value;
                    this.RaisePropertyChanged("FlightDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightID {
            get {
                return this.FlightIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightIDField, value) != true)) {
                    this.FlightIDField = value;
                    this.RaisePropertyChanged("FlightID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightTotal {
            get {
                return this.FlightTotalField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightTotalField, value) != true)) {
                    this.FlightTotalField = value;
                    this.RaisePropertyChanged("FlightTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipCountry {
            get {
                return this.ShipCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipCountryField, value) != true)) {
                    this.ShipCountryField = value;
                    this.RaisePropertyChanged("ShipCountry");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FlightsReference.IFlightsService")]
    public interface IFlightsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightsService/GetFlightTotal", ReplyAction="http://tempuri.org/IFlightsService/GetFlightTotalResponse")]
        string GetFlightTotal(string FlightID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightsService/GetFlightTotal", ReplyAction="http://tempuri.org/IFlightsService/GetFlightTotalResponse")]
        System.Threading.Tasks.Task<string> GetFlightTotalAsync(string FlightID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightsService/GetFlightDetails", ReplyAction="http://tempuri.org/IFlightsService/GetFlightDetailsResponse")]
        WSF_SimpleRESTClient_1.FlightsReference.Flight GetFlightDetails(string FlightID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightsService/GetFlightDetails", ReplyAction="http://tempuri.org/IFlightsService/GetFlightDetailsResponse")]
        System.Threading.Tasks.Task<WSF_SimpleRESTClient_1.FlightsReference.Flight> GetFlightDetailsAsync(string FlightID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightsService/PlaceFlight", ReplyAction="http://tempuri.org/IFlightsService/PlaceFlightResponse")]
        bool PlaceFlight(WSF_SimpleRESTClient_1.FlightsReference.Flight _flight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlightsService/PlaceFlight", ReplyAction="http://tempuri.org/IFlightsService/PlaceFlightResponse")]
        System.Threading.Tasks.Task<bool> PlaceFlightAsync(WSF_SimpleRESTClient_1.FlightsReference.Flight _flight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFlightsServiceChannel : WSF_SimpleRESTClient_1.FlightsReference.IFlightsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlightsServiceClient : System.ServiceModel.ClientBase<WSF_SimpleRESTClient_1.FlightsReference.IFlightsService>, WSF_SimpleRESTClient_1.FlightsReference.IFlightsService {
        
        public FlightsServiceClient() {
        }
        
        public FlightsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlightsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetFlightTotal(string FlightID) {
            return base.Channel.GetFlightTotal(FlightID);
        }
        
        public System.Threading.Tasks.Task<string> GetFlightTotalAsync(string FlightID) {
            return base.Channel.GetFlightTotalAsync(FlightID);
        }
        
        public WSF_SimpleRESTClient_1.FlightsReference.Flight GetFlightDetails(string FlightID) {
            return base.Channel.GetFlightDetails(FlightID);
        }
        
        public System.Threading.Tasks.Task<WSF_SimpleRESTClient_1.FlightsReference.Flight> GetFlightDetailsAsync(string FlightID) {
            return base.Channel.GetFlightDetailsAsync(FlightID);
        }
        
        public bool PlaceFlight(WSF_SimpleRESTClient_1.FlightsReference.Flight _flight) {
            return base.Channel.PlaceFlight(_flight);
        }
        
        public System.Threading.Tasks.Task<bool> PlaceFlightAsync(WSF_SimpleRESTClient_1.FlightsReference.Flight _flight) {
            return base.Channel.PlaceFlightAsync(_flight);
        }
    }
}
